### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by JulienRe** [timssa7/tacoswap-project#1]
Hello,
What will publied here ?
Thank you.

Bonjour, 
Qu'est ce qu'il sera oublié ici?
Merci. Vous pouvez répondre en français si vous êtes Français 👍

**Comment by timssa7** [comment]
Just informations about a New decentralised defi that I'm personally
investing in, and think it's a good investment for all people , also when I
need answers about things I search in your site ,hope it's not a problem

Le lun. 25 janv. 2021 à 09:09, Julien R. <notifications@github.com> a
écrit :
